### ISSUE TITLE
Textures missing from 1.0 to 1.1.0

### ISSUE THREAD

**Issue by Oxosorrel** [thecodewarrior/Catwalk-Mod#1]
Looks like all textures are failing to load. Using just this mod & using Forge 10.13.2.1291. 

I get this error in the client log as I load for each of the blocks in this mod:

[19:26:25] [Client thread/ERROR]: Using missing texture, unable to load catwalkmod:textures/items/steelGrate.png
java.io.FileNotFoundException: catwalkmod:textures/items/steelGrate.png
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:58) ~[brg.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(SourceFile:61) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(SourceFile:52) [bqf.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:538) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by thecodewarrior** [comment]
Just fixed it. Thanks for the heads up... I really need to get in the habit of testing better... Sigh...
